### ISSUE TITLE
Embedded JS Bins don't work on Chrome

### ISSUE THREAD

**Issue by ykarikos** [cyclejs/cyclejs.github.io#24]
The embedded JS Bins on the Basic Examples page (http://cycle.js.org/basic-examples.html) don't show any content on the Output tab while using Chrome 46.0.2490.71 on Mac OS X. The examples work on Firefox 41.0 and Safari 9.0 though. The JS Bins seem to work on Chrome when they are run directly from  jsbin.com.

**Comment by Frikki** [comment]
You should probably raise that issue with JSBin.

**Comment by gregbenner** [comment]
+1 It might entirely be jsbins fault for not rendering but when exploring the never ending list of new libraries and frameworks it's a big plus to see some running examples without having to download a repo for each example. Perhaps Codepen?

**Comment by Frikki** [comment]
@gregbenner I have had really bad experiences with *codepen.io* out of nowhere, and often, entering an infinite loop. I don’t recommend it for Cycle.js.

However, the Web site is being updated as many things have/are changing in Cycle.js. I assume the examples will be fixed, too.

**Comment by staltz** [comment]
The JSBin examples worked perfectly here in Chrome 49.
If it's not a browser problem, then it's a (temporary) JSBin problem. In any case, "fixing" is a bit out of scope for our page.

**Comment by gregbenner** [comment]
Just for your reference... Using evergreen updated Chrome on OSX
  
<img width="1004" alt="screen shot 2015-11-20 at 17 27 19" src="https://cloud.githubusercontent.com/assets/1177690/11306841/36f90a98-8fac-11e5-8165-b312efc9f66e.png">

![59507751](https://cloud.githubusercontent.com/assets/1177690/11306820/1d8a3e56-8fac-11e5-97b6-a6a84014d5e9.jpg)

**Comment by staltz** [comment]
@gregbenner What's your version of Chrome? I was using version 49, it's a Canary version, probably not yet in evergreen Chrome.

**Comment by Frikki** [comment]
@staltz @gregbenner There is a problem with embedded JSBin, at least on Chrome. You can see many errors being logged in the console. It might be related to ES2015/Babel for JavaScript. However, such errors are out of our control.

**Comment by gregbenner** [comment]
Ah see you are correct, https://github.com/jsbin/jsbin/issues/943 jsbin issue
