### ISSUE TITLE
Wrong word placement in "Basic examples"

### ISSUE THREAD

**Issue by sotojuan** [cyclejs/cyclejs.github.io#27]
In the BMI section of the examples page, there's this sentence:

> The problem happens because when we map on bmi$, we do not have anymore the weight and height values.

I think the "anymore" should be at the end of the sentence, like this:

> The problem happens because when we map on bmi$, we do not have the weight and height values anymore.

**Comment by Cmdv** [comment]
@sotojuan :+1: create a Pull Request for it :)
