### ISSUE TITLE
Add "edit on github" link for each page

### ISSUE THREAD

**Issue by staltz** [cyclejs/cyclejs.github.io#31]
Just like this http://bluebirdjs.com/docs/api-reference.html

**Comment by Cmdv** [comment]
I'll pick this up, do you want the `Updated 12 Nov 2015` part too?

**Comment by staltz** [comment]
Not necessary I think

**Comment by Cmdv** [comment]
@nissoh picked it up so all good

**Comment by nissoh** [comment]
@staltz maybe we should move this action next to "open chat" button in a fixed position.

**Comment by staltz** [comment]
@nissoh Have you seen how it looks live? I changed it a bit

**Comment by nissoh** [comment]
@staltz ahh.. yes looks good.

in my comment i meant that we can move it in a fixed position, next to open chat. 
it will be easier to spot on while reading and removes the the need to scroll to the top of the page.
i've also noticed that it is now hidden from screen below 680px.

anyway these are just nitpicking. lets move on (:

**Comment by staltz** [comment]
> i've also noticed that it is now hidden from screen below 680px.

Yeah, on purpose. I thought probably people can't edit stuff on Github from mobile.
