### ISSUE TITLE
Suggestion: perhaps add an extra step to the isolation guide

### ISSUE THREAD

**Issue by axefrog** [cyclejs/cyclejs.github.io#40]
I told a friend about how the component isolation problem in Cycle was now solved, and the immediate reaction was "awww man, so I have to manually call isolate every time I want to instantiate a component?!".

If a component should be isolated in various scenarios, it probably always needs to be isolated. Even if it is only used once, it can probably still be isolated without causing any issues.

Therefore, I'd suggest mentioning that, in developing a component, you could optionally take the burden away from the consumer like so:

```js
function RawComponent(sources) {
    // ...
}

export function Component(sources) {
    return isolate(RawComponent)(sources);
}

// optional for flexibility and convenience:
Component.Unwrapped = RawComponent;
```

Doing this gives the consumer automatic isolation without having to think about it. I understand that some people might want the flexibility or freedom to choose how to isolate, but I'd guess that this is probably going to be an application-wide decision, rather than per-component. It might give newcomers an extra boost of confidence if they realise that exposing their application's components in a pre-isolated fashion is possible, and thus will make the rest of their code leaner.

**Comment by HighOnDrive** [comment]
+1

**Comment by TylorS** [comment]
:+1:

**Comment by staltz** [comment]
I thought that was self evident, but I'll add it. Thanks for suggesting.

**Comment by staltz** [comment]
Done

**Comment by axefrog** [comment]
Nice work! :)

**Comment by MadaraUchiha** [comment]
Given that pretty much every component that's going to be repeated in the DOM (even in a simple loop), or otherwise uses DOM as a state mechanism will **need** to be isolated otherwise it breaks, it seems like redundant boilerplate for the component author.

**Comment by axefrog** [comment]
@MadaraUchiha Two issues;

(1) Cycle is functional in nature; instantiating a component means making a function call. How do you propose that Cycle intercepts arbitrary function calls in JavaScript?

(2) Not all components are UI components. State management, business logic, etc. These don't necessarily qualify for isolation.
