### ISSUE TITLE
The non-isolated components example has another bug.

### ISSUE THREAD

**Issue by b31jung** [cyclejs/cyclejs.github.io#52]
When I run the first example in the "Multiple instances and isolation" section on <http://cycle.js.org/components.html>, only one of the slider label changes with values, and the following paragraph describes like so.
However, I think the both labels should react, since the events for the both inputs are selected by the both.
If I change the embedded `cycle-dom.js` to the up-to-date version, it works like I expected. (http://jsbin.com/qepikuvona/1/edit?html,js,output)
I think it can mislead beginners like me to understand incorrectly, like an event might be removed from source when a component selects it.
Thanks :)

**Comment by staltz** [comment]
Thanks, it's now fixed
