### ISSUE TITLE
getting started npm install

### ISSUE THREAD

**Issue by taylor1791** [cyclejs/cyclejs.github.io#8]
I was following the [getting-started](http://cycle.js.org/getting-started.html) page and I had to run `npm install @cyclejs/cycle-core` instead of `npm install @cycle/core` in order to install it. Is this a mistake?

**Comment by staltz** [comment]
What is your version of npm? Can you run `npm --version`?

**Comment by taylor1791** [comment]
Thank you for your response. I was using v1.4.28. I upgraded to v2.11.3 and I behaved as expected. I noticed that scoped packages were added in v2.0.0. Do you mind if I make a pull request adding this information?

**Comment by staltz** [comment]
Yes, that's what I intend to do asap. Thanks!
